#!/usr/bin/env python3
"""
cpu_test.py — builds the 6502 self-test program and its expectations.

The program exercises the instructions a NES game actually leans on
(loads/stores in every addressing mode, ADC/SBC with carry and overflow,
shifts/rotates, the stack, subroutines, branches, indirect jumps) and
writes one result byte per check into page $03.

It emits build/cpu_test.h, consumed by tools/host_test.c:

    make host-test
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from asm6502 import Assembler, MODE_SIZE  # noqa: E402

ORG = 0x8000

PROGRAM = """
        ; 1 — immediate load/store
        LDA #$42
        STA $0300

        ; 2 — ADC, no carry in
        LDA #$10
        CLC
        ADC #$25
        STA $0301
        PHP
        PLA
        STA $0302          ; carry must be clear here

        ; 3 — ADC with carry out and zero result
        LDA #$FF
        CLC
        ADC #$01
        STA $0303
        PHP
        PLA
        STA $0304          ; carry + zero set

        ; 4 — SBC
        LDA #$50
        SEC
        SBC #$10
        STA $0305

        ; 5 — shifts and rotates
        LDA #$81
        ASL A
        STA $0306
        LDA #$81
        LSR A
        STA $0307
        LDA #$01
        SEC
        ROL A
        STA $0308
        LDA #$01
        SEC
        ROR A
        STA $0309

        ; 6 — absolute indexed
        LDX #$05
        LDA data,X
        STA $030A

        ; 7 — zero-page indexed
        LDX #$02
        LDA zpvals,X
        STA $030B

        ; 8 — (indirect),Y
        LDA #<data
        STA $10
        LDA #>data
        STA $11
        LDY #$03
        LDA ($10),Y
        STA $030C

        ; 9 — subroutine
        JSR sub
        STA $030D

        ; 10 — loop with a branch, ADC accumulation
        LDX #$00
        LDA #$00
loop:
        INX
        CLC
        ADC #$03
        CPX #$0A
        BNE loop
        STA $030E
        STX $030F

        ; 11 — increment/decrement memory
        LDA #$05
        STA $20
        INC $20
        DEC $20
        DEC $20
        LDA $20
        STA $0310

        ; 12 — push/pull
        LDA #$77
        PHA
        LDA #$00
        PLA
        STA $0311

        ; 13 — indirect jump through a vector
        JMP (vec)

target:
        LDA #$AB
        STA $0312
        JMP finished

sub:
        LDA #$99
        RTS

finished:
        JMP finished

data:
        .byte $11,$22,$33,$44,$55,$66,$77,$88
zpvals:
        .byte $A1,$A2,$A3,$A4
vec:
        .word target
"""

# (address, mask, expected, description) — masked compare, so tests that
# only care about a couple of flag bits do not depend on the unused bits.
EXPECTS = [
    (0x0300, 0xFF, 0x42, "LDA #imm / STA abs"),
    (0x0301, 0xFF, 0x35, "ADC #$25 without carry"),
    (0x0302, 0x01, 0x00, "ADC carry flag clear"),
    (0x0303, 0xFF, 0x00, "ADC #$01 wraps FF+1 to 00"),
    (0x0304, 0x03, 0x03, "ADC sets carry and zero"),
    (0x0305, 0xFF, 0x40, "SBC with borrow cleared"),
    (0x0306, 0xFF, 0x02, "ASL A"),
    (0x0307, 0xFF, 0x40, "LSR A"),
    (0x0308, 0xFF, 0x03, "ROL A with carry in"),
    (0x0309, 0xFF, 0x80, "ROR A with carry in"),
    (0x030A, 0xFF, 0x66, "LDA abs,X"),
    (0x030B, 0xFF, 0xA3, "LDA zp,X"),
    (0x030C, 0xFF, 0x44, "LDA (zp),Y"),
    (0x030D, 0xFF, 0x99, "JSR/RTS return value"),
    (0x030E, 0xFF, 0x1E, "loop accumulates 10 x 3"),
    (0x030F, 0xFF, 0x0A, "loop counter reached 10"),
    (0x0310, 0xFF, 0x04, "INC/DEC memory"),
    (0x0311, 0xFF, 0x77, "PHA/PLA round trip"),
    (0x0312, 0xFF, 0xAB, "JMP (indirect) landed correctly"),
]


def build():
    a = Assembler(ORG)
    for ln in PROGRAM.strip("\n").splitlines():
        a.add(ln)
    image = a.assemble()
    return image, a.labels


def main():
    image, labels = build()
    out = []
    out.append("/* GENERATED by tools/cpu_test.py — do not edit. */")
    out.append(f"#define CPU_TEST_ORG 0x{ORG:04X}U")
    out.append(f"#define CPU_TEST_LEN {len(image)}U")
    out.append("static const unsigned char cpu_test_program[CPU_TEST_LEN] = {")
    for i in range(0, len(image), 12):
        out.append("    " + ", ".join(f"0x{b:02X}" for b in image[i:i + 12]) + ",")
    out.append("};")
    out.append("typedef struct { unsigned short addr; unsigned char mask, value;"
               " const char *name; } cpu_expect_t;")
    out.append("static const cpu_expect_t cpu_expects[] = {")
    for addr, mask, val, name in EXPECTS:
        out.append(f'    {{ 0x{addr:04X}, 0x{mask:02X}, 0x{val:02X}, "{name}" }},')
    out.append("};")
    out.append("#define CPU_EXPECT_COUNT "
               "(sizeof(cpu_expects) / sizeof(cpu_expects[0]))")
    os.makedirs("build", exist_ok=True)
    path = os.path.join("build", "cpu_test.h")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {path}: {len(image)} bytes of 6502 code, "
          f"{len(EXPECTS)} checks; labels: "
          + ", ".join(f"{k}=${v:04X}" for k, v in labels.items()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
