#!/usr/bin/env python3
"""
diff_setup.py — prepares the old-vs-new differential test.

Builds build/difftest/old_cpu_core/ containing the *previous* core exactly
as committed (cpu6502.c + cpu_ops.h from the given revision) plus a
nesmem.h whose externs are renamed, so that the old core and the new one
can be linked into one program without their globals colliding.

Usage:  python3 tools/diff_setup.py [revision]
        python3 tools/diff_setup.py --current      (pre-change tree as "old")
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "build", "difftest", "old_cpu_core")

# Every global the old core defines or declares, plus its entry points and
# the bus helpers it calls, gets an OLD_ prefix.
PREFIX = """\
/* GENERATED by tools/diff_setup.py — symbol renaming for the old core.
 * It is force-included (-include) before the old cpu6502.c, so the old
 * core's own cpu6502.h/nesmem.h (also staged here, from the same
 * revision) declare OLD_-prefixed symbols. */
#pragma once
#define cpu_t          OLD_cpu_t
#define cpu            OLD_cpu
#define cpu_stall      OLD_cpu_stall
#define cpu_reset      OLD_cpu_reset
#define cpu_step       OLD_cpu_step
#define cpu_run        OLD_cpu_run
#define cpu_nmi        OLD_cpu_nmi
#define cpu_irq        OLD_cpu_irq
/* the bus symbols: the old core's nesmem.h below points them at the
 * harness's own memory so both cores see the same bytes */
#define bus_read            OLD_bus_read
#define bus_write           OLD_bus_write
#define nes_ram_2k          OLD_nes_ram_2k
#define nes_prg             OLD_nes_prg
#define nes_bus_read_slow   OLD_nes_bus_read_slow
#define nes_bus_write_slow  OLD_nes_bus_write_slow
"""

OLDMEM = """\
/* GENERATED by tools/diff_setup.py — the old core's view of memory: the
 * same bytes the new core sees, under renamed symbols. */
#pragma once
#include <stdint.h>

extern uint8_t OLD_nes_ram_2k[0x800];
extern const uint8_t *OLD_nes_prg[4];

uint8_t OLD_nes_bus_read_slow(uint16_t addr);
void    OLD_nes_bus_write_slow(uint16_t addr, uint8_t value);

static inline uint8_t OLD_bus_read(uint16_t addr)
{
    if (addr < 0x2000)
        return OLD_nes_ram_2k[addr & 0x7FF];
    if (addr >= 0x8000)
        return OLD_nes_prg[(addr >> 13) & 3][addr & 0x1FFF];
    return OLD_nes_bus_read_slow(addr);
}

static inline void OLD_bus_write(uint16_t addr, uint8_t value)
{
    if (addr < 0x2000) {
        OLD_nes_ram_2k[addr & 0x7FF] = value;
        return;
    }
    OLD_nes_bus_write_slow(addr, value);
}
"""


def git_show(rev, path):
    return subprocess.check_output(["git", "show", f"{rev}:{path}"], cwd=ROOT)


def main():
    rev = "HEAD"
    src_cpu = None
    src_ops = None
    src_hdr = None
    src_mem = None
    for a in sys.argv[1:]:
        if a == "--current":
            src_cpu = open(os.path.join(ROOT, "src/cpu6502.c"), "rb").read()
            src_ops = open(os.path.join(ROOT, "src/cpu_ops.h"), "rb").read()
            src_hdr = open(os.path.join(ROOT, "src/cpu6502.h"), "rb").read()
            src_mem = open(os.path.join(ROOT, "src/nesmem.h"), "rb").read()
        else:
            rev = a

    os.makedirs(OUT, exist_ok=True)
    if src_cpu is None:
        src_cpu = git_show(rev, "src/cpu6502.c")
        src_ops = git_show(rev, "src/cpu_ops.h")
        src_hdr = git_show(rev, "src/cpu6502.h")
        # the old nesmem.h is only a reference; the harness supplies its
        # own renamed copy below
        src_mem = b""
        label = f"revision {rev}"
    else:
        label = "current working tree"

    with open(os.path.join(OUT, "cpu6502.c"), "wb") as f:
        f.write(src_cpu)
    with open(os.path.join(OUT, "cpu_ops.h"), "wb") as f:
        f.write(src_ops)
    with open(os.path.join(OUT, "cpu6502.h"), "wb") as f:
        f.write(src_hdr)
    with open(os.path.join(OUT, "diff_prefix.h"), "w") as f:
        f.write(PREFIX)
    with open(os.path.join(OUT, "nesmem.h"), "w") as f:
        f.write(OLDMEM)

    print(f"old core staged from {label} in {OUT}")
    print("  cpu6502.c %d bytes, cpu_ops.h %d bytes, cpu6502.h %d bytes" %
          (len(src_cpu), len(src_ops), len(src_hdr)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
