#!/usr/bin/env python3
"""
rom2c.py — embed a .nes cartridge image into the firmware.

    python3 tools/rom2c.py build/test.nes src/rom_data.c
"""
import sys


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "build/test.nes"
    dst = sys.argv[2] if len(sys.argv) > 2 else "src/rom_data.c"
    data = open(src, "rb").read()

    out = ["/* GENERATED by tools/rom2c.py — do not edit. */",
           f"/* cartridge: {src} ({len(data)} bytes) */",
           "#include <stdint.h>",
           "",
           f"const uint32_t nes_rom_len = {len(data)}u;",
           "const uint8_t nes_rom[] = {"]
    for i in range(0, len(data), 16):
        out.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    out.append("};")
    open(dst, "w").write("\n".join(out) + "\n")
    print(f"wrote {dst}: {len(data)} bytes embedded")


if __name__ == "__main__":
    main()
