/*
 * cpu6502.c — the emulated 6502 core.
 *
 * What this module owns: the registers, the status flags, the stack, the
 * addressing modes and the 256 opcodes, plus the cycle cost of each
 * instruction (the PPU and the frame loop pace themselves by that
 * number, so the costs are part of the contract, not a detail). What it
 * deliberately does not own: anything about the NES — no address is
 * decoded here, and no memory is stored here.
 *
 * What it assumes about the layer below: two byte-wide accessors,
 * bus_read(addr) and bus_write(addr, value). The core never learns
 * whether they touch RAM, cartridge ROM, a mapper register or a PPU
 * register, which is why this file compiles and runs unchanged on the PC
 * (`tools/host_test.c`, `tools/host_render.c`, `tools/diff_test.c`) —
 * reproducing a bug on the PC is the first step of every fix. Whether
 * the accessors are calls into nes.c or the inline fast paths of
 * nesmem.h is a link-time choice (NES_BUS_INLINE); this file only needs
 * them declared, and cpu6502.h does that.
 *
 * The circuit quirks that shaped the file:
 *   - the 2A03 is a 6502 without decimal mode, so the D flag is stored
 *     and pushed like any other bit but never changes a result; SED/CLD
 *     and PLP work, ADC/SBC stay binary. That matches the real chip.
 *   - the CPU is memory-mapped into the same 64 KB as everything else,
 *     so the stack is not a private buffer but page 1 of that space and
 *     the three vectors live at the top of it.
 *   - the indirect JMP reproduces the chip's page-boundary bug, and
 *     branches cost one cycle more when they cross a page; both are
 *     visible in games, so both are emulated rather than fixed.
 *
 * Structure, and why it is unusual:
 *   - the 6502 registers live in *automatic variables inside cpu_run()*
 *     (pc/a/x/y/sp/p), together with the per-instruction cycle counter
 *     (cyc) and the page-cross flag (page). They are ordinary locals
 *     whose address is never taken, so the compiler may keep them in
 *     host registers across the whole batch — across the bus reads and
 *     writes too, which is exactly what a file-scope (static) cache
 *     could not do: a static object may not stay in a register across a
 *     memory access it cannot be proved not to alias.
 *   - because a `static inline` function cannot see its caller's locals,
 *     everything that must touch those locals — the bus accessors, the
 *     stack, the addressing modes, the ALU/flag helpers and the generated
 *     opcode bodies — is a macro over them. All of those macros are
 *     defined inside cpu_run(), right above the dispatch loop, and are
 *     #undef'd at the bottom of it. The one exception is `bus_read`/
 *     `bus_write` themselves (nesmem.h), which take the address as an
 *     argument and are shared with the PPU.
 *   - the opcode dispatch in cpu_ops.h is generated by tools/gen_6502.py
 *     and is written entirely in those macros, one case per opcode:
 *     a load is `a = RD(ZP()); SETZN(a)`, an ALU op is `A_ORA(RD(INX()))`,
 *     a store is `WR(ABS_(), a)`, a branch is `BRANCH_TAKE(!(p & F_Z))`.
 *     That is why the file looks like one long function: the registers
 *     must be locals of the function the instruction bodies are inlined
 *     into, so the batch loop, the dispatch and the accounting cannot be
 *     split off into helpers without giving up the registers.
 *
 * Each macro evaluates every argument at most once, in the same places
 * the functions it replaced evaluated it, so an operand with a side
 * effect (INX(), RD(...), PULL()) is still evaluated exactly once;
 * nowhere does the generated expression duplicate one. Statement-like
 * macros (BRANCH_TAKE, JMP_IND, BRK, the stack pushes) are do-while
 * blocks whose temporaries are named m6502_* so a nested use cannot
 * shadow its caller's variable.
 *
 * `cpu` still holds the honest current state: cpu_run() copies it in at
 * the top and writes it back at the bottom, and every entry point that
 * changes the registers from outside a batch (cpu_reset, cpu_nmi,
 * cpu_irq) touches the struct directly. That matters for nes.c, which
 * calls cpu_nmi()/cpu_irq() between cpu_run() batches, and for the SWD
 * debugger, which reads `cpu` while the board runs.
 */
#include "cpu6502.h"

#ifdef NES_BUS_INLINE
#include "nesmem.h"     /* inlined fast paths for RAM and cartridge ROM */
#endif

cpu_t cpu;

/* charged by the bus for things like OAM DMA: the CPU really does stop
 * for these cycles, so they must come out of the frame budget too. The
 * dispatch loop below adds it to the instruction in progress and zeroes
 * it again, so one stall is charged to exactly one instruction. */
int cpu_stall;

/* ------------------------- 6502 constants ------------------------- */
/* The stack is memory like any other: the chip hardwires page 1, and the
 * core starts a program with sp at 0xFD, which is where the Famicom/NES
 * reset code leaves it. A program that never touches sp therefore has
 * 253 usable bytes below it. */
#define STACK_PAGE        ((uint16_t)0x0100)
#define SP_AFTER_RESET    0xFD

/* The three vectors sit in the top page in the chip's fixed order. On a
 * NES only the NMI comes from outside (the PPU raises it at vblank); IRQ
 * comes from the mapper, and RESET is the power-on line, which this core
 * handles in cpu_reset() rather than as an interrupt. */
#define NMI_VECTOR        ((uint16_t)0xFFFA)
#define RESET_VECTOR      ((uint16_t)0xFFFC)
#define IRQ_VECTOR        ((uint16_t)0xFFFE)

/* The 6502 splits its 16-bit addresses into 256-byte pages, and its
 * arithmetic uses those seams:
 *   - a read (never a write) through an indexed address costs one extra
 *     cycle when the index carries into the page's high byte: the
 *     addressing macros here only raise the `page` flag, and the
 *     generated case in cpu_ops.h decides whether to charge it;
 *   - a zero-page pointer wraps inside page 0 instead of running into
 *     page 1, which is how a program keeps a 256-byte table in bounds;
 *   - an indirect JMP reads the second half of its pointer in the same
 *     page as the first half, which is the chip's best-known bug. */
#define PAGE_MASK         ((uint16_t)0xFF00u)
#define ZERO_PAGE_MASK    0xFFu

/* Taking an interrupt is seven cycles: three to push pc and the status
 * byte, two to read the vector, two of overhead. */
#define INTERRUPT_CYCLES  7

/* --------------------------- macro toolkit ------------------------ */
/* These are statement/expression macros over the locals of cpu_run();
 * they are defined inside that function and #undef'd at its end. The
 * block below is the definition table the rest of the file (and the
 * generator) is written against; it is kept in one place so the macro
 * names, the generator and this comment cannot drift apart. */

/* ---- bus ---------------------------------------------------------- */
/* FETCH8()  read the byte at pc and step past it
 * RD(ad)    read one byte
 * WR(ad,v)  write one byte (v is evaluated exactly once; it is assigned
 *           to the block-local `t` first, which is also what keeps an
 *           operand like RD(e++) from being evaluated twice)           */

/* ---- stack -------------------------------------------------------- */
/* PUSH(v) / PULL() / PUSH16(v) / PULL16()
 * PULL16() uses a do-while block rather than a comma expression so that
 * the low byte is read from memory before the index is bumped again —
 * the same order the old `pull()` helper used.                         */

/* ---- addressing --------------------------------------------------- */
/* IMM() ZP() ZPX() ZPY() ABS_() ABX() ABY() INX() INY()
 * All of them take no arguments, so none of them can be evaluated twice
 * by its caller, and each updates pc exactly as the old helpers did.
 * ABX()/ABY()/INY() also set `page`.                                  */

/* ---- ALU and flags ------------------------------------------------ */
/* SETZN(v) A_ORA(v) A_AND(v) A_EOR(v) A_ADC(v) A_SBC(v)
 * A_CMP(v) A_CPX(v) A_CPY(v) CMP_REG(r,v)
 * ASL(v) LSR(v) ROL(v) ROR(v) INC8(v) DEC8(v)   (value-returning)
 * SETZN() double-evaluates its argument — `v` appears in two tests —
 * so every caller passes a variable, never a function call with a side
 * effect, exactly as the old `setzn()` callers did.                   */

/* ---- control flow ------------------------------------------------- */
/* BRANCH_TAKE(c) JMP_IND() BRK() RTS() RTI()
 * BRANCH_TAKE takes the condition as an int expression, evaluated once. */

/* --------------------------- public API --------------------------- */
/* Everything outside cpu_run() works directly on the `cpu` struct: it
 * is not the hot path and the struct is honest at those boundaries. */

void cpu_reset(void)
{
    cpu.a = cpu.x = cpu.y = 0;
    cpu.sp = SP_AFTER_RESET;
    cpu.p  = F_I | F_U;         /* no IRQs until the program says so */
    cpu.pc = (uint16_t)(bus_read(RESET_VECTOR) | (bus_read(RESET_VECTOR + 1) << 8));
    cpu.cycles = 0;
    cpu.instructions = 0;
}

/* shared by cpu_nmi()/cpu_irq(): push pc and the status byte, mask IRQs
 * and jump through the vector at `vector`. The pushed status has B set
 * (this is an interrupt, not a BRK) and U forced to 1, and the B bit
 * pushed here is the one PLP and RTI throw away again — the flag only
 * ever exists on the stack. */
static void interrupt_enter(uint16_t vector)
{
    bus_write((uint16_t)(STACK_PAGE + cpu.sp--), (uint8_t)(cpu.pc >> 8));
    bus_write((uint16_t)(STACK_PAGE + cpu.sp--), (uint8_t)(cpu.pc & 0xFF));
    bus_write((uint16_t)(STACK_PAGE + cpu.sp--), (uint8_t)((cpu.p & ~F_B) | F_U));
    cpu.p |= F_I;
    cpu.pc = (uint16_t)(bus_read(vector) | (bus_read((uint16_t)(vector + 1)) << 8));
    cpu.cycles += INTERRUPT_CYCLES;
}

/* called from the frame loop between cpu_run() batches: the struct is
 * honest there (cpu_run() wrote it back when it returned), so the
 * interrupt can work on it directly. An NMI cannot be masked, which is
 * why this one returns nothing while cpu_irq() reports whether it was
 * taken — nes.c has to know, because a masked IRQ line stays asserted. */
void cpu_nmi(void)
{
    interrupt_enter(NMI_VECTOR);
}

bool cpu_irq(void)
{
    if (cpu.p & F_I)            /* masked: the line stays asserted */
        return false;
    interrupt_enter(IRQ_VECTOR);
    return true;
}

/* One instruction, with the same external behaviour as always: one
 * instruction runs, the registers end up back in `cpu` and the cycle
 * count is returned.
 *
 * A budget of one cycle buys exactly one instruction because every
 * instruction charges at least two (see the `cyc == 0` guard below), so
 * cpu_run() cannot fit a second one into it: the budget is a whole
 * number of instructions, never a fraction of one. */
int cpu_step(void)
{
    return cpu_run(1);
}

/* The hot path: copy the registers into true locals once, run
 * instructions against them until the cycle budget is spent, copy them
 * back once. The macros below are the only way the instruction bodies
 * can reach those locals. The batch loop inside cpu_ops.h publishes
 * cpu.cycles and cpu.instructions as it goes, because those two are the
 * debugger's and the frame loop's counters and nothing else has to be
 * woken up per instruction. */
int cpu_run(int32_t budget)
{
    uint16_t pc = cpu.pc;
    uint8_t  a = cpu.a, x = cpu.x, y = cpu.y, sp = cpu.sp, p = cpu.p;
    int      cyc = 0, page = 0;          /* also locals: never address-taken */
    int32_t  done = 0;
    uint32_t ins  = 0;

    /* ------------------------------ bus --------------------------- */
    /* RD(ad)/WR(ad,v) take the address (and the value) as arguments, so
     * the operand expression is evaluated exactly once — ad here, and in
     * WR the value as well. That single evaluation is what makes
     * `WR(e, ASL(RD(e)))` (a read-modify-write of one address) safe: the
     * value argument, side effect and all, is evaluated once, into
     * m6502_w, before the write. */
#define FETCH8()          (bus_read(pc++))
#define RD(ad)            (bus_read(ad))
#define WR(ad, v)         do { uint8_t m6502_w = (uint8_t)(v); bus_write((ad), m6502_w); } while (0)

    /* ----------------------------- stack -------------------------- */
    /* same shape as the old push()/pull(): `sp--`/`++sp` appear once */
#define PUSH(v)           do { uint8_t m6502_s = (uint8_t)(v); bus_write((uint16_t)(STACK_PAGE + sp--), m6502_s); } while (0)
#define PULL()            ((uint8_t)bus_read((uint16_t)(STACK_PAGE + ++sp)))
    /* pushes are three separate statements, so pc/p has no way to be
     * evaluated more than once by this macro */
#define PUSH16(v)         do { uint16_t m6502_t = (uint16_t)(v); PUSH((uint8_t)(m6502_t >> 8)); PUSH((uint8_t)(m6502_t & 0xFF)); } while (0)
    /* a block, not a comma expression: the operand is cast once, and the
     * low byte is read before the second ++sp */
#define PULL16()          ((uint16_t)({ uint8_t m6502_lo = PULL(); (uint16_t)(m6502_lo | (PULL() << 8)); }))

    /* -------------------------- addressing ------------------------ */
    /* IMM() is the odd one out: it hands back the address of the operand
     * byte, not the byte, because every caller reads through it
     * (`RD(IMM())`) — it only steps pc, exactly as the old helper. */
#define IMM()             ((uint16_t)(pc++))
#define ZP()              (FETCH8())
#define ZPX()             (uint16_t)((FETCH8() + x) & ZERO_PAGE_MASK)
#define ZPY()             (uint16_t)((FETCH8() + y) & ZERO_PAGE_MASK)
#define ABS_()            ({ uint8_t m6502_lo = FETCH8(); uint8_t m6502_hi = FETCH8(); (uint16_t)(m6502_lo | (m6502_hi << 8)); })
#define ABX()             ({ uint16_t m6502_b = ABS_(); uint16_t m6502_e = (uint16_t)(m6502_b + x); page = (((m6502_b ^ m6502_e) & PAGE_MASK) ? 1 : 0); m6502_e; })
#define ABY()             ({ uint16_t m6502_b = ABS_(); uint16_t m6502_e = (uint16_t)(m6502_b + y); page = (((m6502_b ^ m6502_e) & PAGE_MASK) ? 1 : 0); m6502_e; })
/* (indirect,X): zero-page pointer with wraparound */
#define INX()             ({ uint8_t m6502_z = (uint8_t)(FETCH8() + x); uint8_t m6502_lo = RD(m6502_z); uint8_t m6502_hi = RD((uint8_t)(m6502_z + 1)); (uint16_t)(m6502_lo | (m6502_hi << 8)); })
/* (indirect),Y: zero-page pointer, then add Y */
#define INY()             ({ uint8_t m6502_z = FETCH8(); uint8_t m6502_lo = RD(m6502_z); uint8_t m6502_hi = RD((uint8_t)(m6502_z + 1)); uint16_t m6502_b = (uint16_t)(m6502_lo | (m6502_hi << 8)); uint16_t m6502_e = (uint16_t)(m6502_b + y); page = (((m6502_b ^ m6502_e) & PAGE_MASK) ? 1 : 0); m6502_e; })

    /* ----------------------------- flags -------------------------- */
    /* `v` is used twice here (once per flag); every caller passes a
     * variable, as the old setzn() callers did */
#define SETZN(v)          (p = (uint8_t)(((p) & ~(F_Z | F_N)) | ((v) == 0 ? F_Z : 0) | ((v) & F_N)))

    /* ------------------------------ ALU --------------------------- */
    /* The A_* macros use their operand more than once (value plus flags),
     * so the generator puts every memory operand into a `uint8_t v` local
     * first: `uint8_t v = RD(ZP()); A_ADC(v);` — the old form,
     * a_adc(rd(zp())), evaluated the function argument once, and this is
     * the same single evaluation. A_CMP/A_CPX/A_CPY go through CMP_REG,
     * which also uses its operand twice for the same reason. SETZN(v) is
     * likewise passed only a variable. Passing a call with a side effect
     * straight to any of these would evaluate it twice. */
#define A_ORA(v)          do { a = (uint8_t)(a | (uint8_t)(v)); SETZN(a); } while (0)
#define A_AND(v)          do { a = (uint8_t)(a & (uint8_t)(v)); SETZN(a); } while (0)
#define A_EOR(v)          do { a = (uint8_t)(a ^ (uint8_t)(v)); SETZN(a); } while (0)
#define A_ADC(v)          do { \
        unsigned m6502_c = (p & F_C) ? 1u : 0u; \
        unsigned m6502_r = (unsigned)a + (unsigned)(uint8_t)(v) + m6502_c; \
        uint8_t  m6502_s = (uint8_t)m6502_r; \
        p &= (uint8_t)~F_C; \
        if (m6502_r > 0xFFu) p |= F_C; \
        if (~(a ^ (uint8_t)(v)) & (a ^ m6502_s) & 0x80) p |= F_V; \
        a = m6502_s; \
        SETZN(m6502_s); \
    } while (0)
#define A_SBC(v)          A_ADC((uint8_t)~(uint8_t)(v))
#define CMP_REG(r, v)     do { \
        unsigned m6502_t = (unsigned)(r) - (unsigned)(uint8_t)(v); \
        p &= (uint8_t)~F_C; \
        if ((uint8_t)(r) >= (uint8_t)(v)) p |= F_C; \
        SETZN((uint8_t)m6502_t); \
    } while (0)
#define A_CMP(v)          CMP_REG(a, v)
#define A_CPX(v)          CMP_REG(x, v)
#define A_CPY(v)          CMP_REG(y, v)
#define ASL(v)            ({ uint8_t m6502_v = (uint8_t)(v); uint8_t m6502_r = (uint8_t)(m6502_v << 1); p = (uint8_t)((p & ~F_C) | ((m6502_v >> 7) & 1)); SETZN(m6502_r); m6502_r; })
#define LSR(v)            ({ uint8_t m6502_v = (uint8_t)(v); uint8_t m6502_r = (uint8_t)(m6502_v >> 1); p = (uint8_t)((p & ~F_C) | (m6502_v & 1)); SETZN(m6502_r); m6502_r; })
#define ROL(v)            ({ uint8_t m6502_v = (uint8_t)(v); uint8_t m6502_c = (p & F_C) ? 1 : 0; uint8_t m6502_r = (uint8_t)((m6502_v << 1) | m6502_c); p = (uint8_t)((p & ~F_C) | ((m6502_v >> 7) & 1)); SETZN(m6502_r); m6502_r; })
#define ROR(v)            ({ uint8_t m6502_v = (uint8_t)(v); uint8_t m6502_c = (p & F_C) ? 1 : 0; uint8_t m6502_r = (uint8_t)((m6502_v >> 1) | (m6502_c << 7)); p = (uint8_t)((p & ~F_C) | (m6502_v & 1)); SETZN(m6502_r); m6502_r; })
#define INC8(v)           ({ uint8_t m6502_v = (uint8_t)((uint8_t)(v) + 1); SETZN(m6502_v); m6502_v; })
#define DEC8(v)           ({ uint8_t m6502_v = (uint8_t)((uint8_t)(v) - 1); SETZN(m6502_v); m6502_v; })

    /* --------------------------- control flow --------------------- */
    /* BRANCH_TAKE(c) evaluates the condition once, into a local. Both
     * instruction lengths are fixed: the not-taken branch is two cycles
     * and the displacement byte is still fetched, which is why the fetch
     * happens before the test. The penalty is for the destination page,
     * and the same `pc + (int8_t)offset` also covers the backward branch
     * — a jump from $0100 to $00FF is one page crossing, not a borrow. */
#define BRANCH_TAKE(c)    do { \
        int m6502_take = (c) ? 1 : 0; \
        int8_t m6502_off = (int8_t)FETCH8(); \
        if (!m6502_take) { cyc = 2; } \
        else { \
            uint16_t m6502_o = pc; \
            pc = (uint16_t)(pc + m6502_off); \
            cyc = 3 + (((m6502_o ^ pc) & PAGE_MASK) ? 1 : 0); \
        } \
    } while (0)
    /* the famous page-boundary bug of the indirect jump: the second half
     * of the pointer is read from the start of the *same* page, not from
     * the next one, so a vector sitting at $xxFF yields
     * ($xx00 << 8) | low. The chip does this, and a program that keeps a
     * jump table across the seam relies on it — "fixing" it here would
     * move those jumps somewhere else entirely. */
#define JMP_IND()         do { \
        uint16_t m6502_p = ABS_(); \
        uint16_t m6502_lo = RD(m6502_p); \
        uint16_t m6502_hi = RD((uint16_t)((m6502_p & 0xFF00) | ((m6502_p + 1) & 0xFF))); \
        pc = (uint16_t)(m6502_lo | (m6502_hi << 8)); \
    } while (0)
#define BRK()             do { \
        PUSH16((uint16_t)(pc + 1)); \
        PUSH((uint8_t)(p | F_B | F_U)); \
        p |= F_I; \
        pc = (uint16_t)(RD(0xFFFE) | (RD(0xFFFF) << 8)); \
    } while (0)
#define RTS()             do { pc = (uint16_t)(PULL16() + 1); } while (0)
#define RTI()             do { p = (uint8_t)((PULL() & ~F_B) | F_U); pc = PULL16(); } while (0)

    /* ------------------------- instructions ----------------------- */
    /* CYCLES(n) records how many master cycles the instruction burned;
     * the generated loop reads `cyc` for the batch budget. Also note
     * that a run of bus accesses is always split into separate full
     * expressions (one statement or one comma-separated initialiser
     * each), because `pc++` twice in one expression would be
     * unsequenced. */
#define CYCLES(n)         (cyc = (n))

    /* ------------------- generated instruction loop ---------------- */
    /* cpu_ops.h, produced by tools/gen_6502.py, is the whole dispatch
     * loop: the 256 cases of the switch, the fetch of the opcode, the
     * batch loop around them and the cycle accounting. It is generated
     * rather than a macro in EXEC_ONE() shape because a #include may not
     * appear in a macro body, and the cases have to be in the switch —
     * so the generator writes the loop, in the macros above, and this
     * file supplies the locals it runs on. cpu.cycles/instructions are
     * the only struct fields the loop touches; everything else is
     * local. */
#include "cpu_ops.h"

    cpu.pc = pc;
    cpu.a  = a;
    cpu.x  = x;
    cpu.y  = y;
    cpu.sp = sp;
    cpu.p  = p;
    cpu.instructions += ins;

#undef FETCH8
#undef RD
#undef WR
#undef PUSH
#undef PULL
#undef PUSH16
#undef PULL16
#undef IMM
#undef ZP
#undef ZPX
#undef ZPY
#undef ABS_
#undef ABX
#undef ABY
#undef INX
#undef INY
#undef SETZN
#undef A_ORA
#undef A_AND
#undef A_EOR
#undef A_ADC
#undef A_SBC
#undef CMP_REG
#undef A_CMP
#undef A_CPX
#undef A_CPY
#undef ASL
#undef LSR
#undef ROL
#undef ROR
#undef INC8
#undef DEC8
#undef BRANCH_TAKE
#undef JMP_IND
#undef BRK
#undef RTS
#undef RTI
#undef CYCLES

    return (int)done;
}
