/* GENERATED by tools/gen_6502.py — do not edit by hand. */
/* One case per opcode: addressing helper + base cycle count. */
    case 0x00: brk(); CYCLES(7); break;  /* BRK */
    case 0x01: a_ora(rd(inx())); CYCLES(6); break;  /* ORA inx */
    case 0x02: CYCLES(2); break;  /* illegal -> NOP */
    case 0x03: { uint16_t e = inx(); uint8_t v = asl(rd(e)); wr(e, v); a_ora(v); } CYCLES(6); break;  /* SLO inx */
    case 0x04: CYCLES(2); break;  /* illegal -> NOP */
    case 0x05: a_ora(rd(zp())); CYCLES(3); break;  /* ORA zp */
    case 0x06: { uint16_t e = zp(); wr(e, asl(rd(e))); } CYCLES(5); break;  /* ASL zp */
    case 0x07: { uint16_t e = zp(); uint8_t v = asl(rd(e)); wr(e, v); a_ora(v); } CYCLES(5); break;  /* SLO zp */
    case 0x08: push(cpu.p | F_B | F_U); CYCLES(3); break;  /* PHP */
    case 0x09: a_ora(rd(imm())); CYCLES(2); break;  /* ORA imm */
    case 0x0A: cpu.a = asl(cpu.a); CYCLES(2); break;  /* ASL A */
    case 0x0B: CYCLES(2); break;  /* illegal -> NOP */
    case 0x0C: CYCLES(2); break;  /* illegal -> NOP */
    case 0x0D: a_ora(rd(abs_())); CYCLES(4); break;  /* ORA abs */
    case 0x0E: { uint16_t e = abs_(); wr(e, asl(rd(e))); } CYCLES(6); break;  /* ASL abs */
    case 0x0F: { uint16_t e = abs_(); uint8_t v = asl(rd(e)); wr(e, v); a_ora(v); } CYCLES(6); break;  /* SLO abs */
    case 0x10: CYCLES(branch(!(cpu.p & F_N))); break;  /* BPL rel */
    case 0x11: a_ora(rd(iny())); CYCLES(5 + page); break;  /* ORA iny */
    case 0x12: CYCLES(2); break;  /* illegal -> NOP */
    case 0x13: { uint16_t e = iny(); uint8_t v = asl(rd(e)); wr(e, v); a_ora(v); } CYCLES(6); break;  /* SLO iny */
    case 0x14: CYCLES(2); break;  /* illegal -> NOP */
    case 0x15: a_ora(rd(zpx())); CYCLES(4); break;  /* ORA zpx */
    case 0x16: { uint16_t e = zpx(); wr(e, asl(rd(e))); } CYCLES(6); break;  /* ASL zpx */
    case 0x17: { uint16_t e = zpx(); uint8_t v = asl(rd(e)); wr(e, v); a_ora(v); } CYCLES(6); break;  /* SLO zpx */
    case 0x18: cpu.p &= (uint8_t)~F_C; CYCLES(2); break;  /* CLC */
    case 0x19: a_ora(rd(aby())); CYCLES(4 + page); break;  /* ORA aby */
    case 0x1A: CYCLES(2); break;  /* illegal -> NOP */
    case 0x1B: { uint16_t e = aby(); uint8_t v = asl(rd(e)); wr(e, v); a_ora(v); } CYCLES(7); break;  /* SLO aby */
    case 0x1C: CYCLES(2); break;  /* illegal -> NOP */
    case 0x1D: a_ora(rd(abx())); CYCLES(4 + page); break;  /* ORA abx */
    case 0x1E: { uint16_t e = abx(); wr(e, asl(rd(e))); } CYCLES(7); break;  /* ASL abx */
    case 0x1F: { uint16_t e = abx(); uint8_t v = asl(rd(e)); wr(e, v); a_ora(v); } CYCLES(7); break;  /* SLO abx */
    case 0x20: { uint16_t t = abs_(); push16((uint16_t)(cpu.pc - 1)); cpu.pc = t; CYCLES(6); } break;  /* JSR abs */
    case 0x21: a_and(rd(inx())); CYCLES(6); break;  /* AND inx */
    case 0x22: CYCLES(2); break;  /* illegal -> NOP */
    case 0x23: { uint16_t e = inx(); uint8_t v = rol(rd(e)); wr(e, v); a_and(v); } CYCLES(6); break;  /* RLA inx */
    case 0x24: { uint8_t v = rd(zp()); cpu.p = (uint8_t)((cpu.p & ~(F_N | F_V | F_Z)) | (v & (F_N | F_V)) | ((cpu.a & v) ? 0 : F_Z)); } CYCLES(3); break;  /* BIT zp */
    case 0x25: a_and(rd(zp())); CYCLES(3); break;  /* AND zp */
    case 0x26: { uint16_t e = zp(); wr(e, rol(rd(e))); } CYCLES(5); break;  /* ROL zp */
    case 0x27: { uint16_t e = zp(); uint8_t v = rol(rd(e)); wr(e, v); a_and(v); } CYCLES(5); break;  /* RLA zp */
    case 0x28: cpu.p = (uint8_t)((pull() & (uint8_t)~F_B) | F_U); CYCLES(4); break;  /* PLP */
    case 0x29: a_and(rd(imm())); CYCLES(2); break;  /* AND imm */
    case 0x2A: cpu.a = rol(cpu.a); CYCLES(2); break;  /* ROL A */
    case 0x2B: CYCLES(2); break;  /* illegal -> NOP */
    case 0x2C: { uint8_t v = rd(abs_()); cpu.p = (uint8_t)((cpu.p & ~(F_N | F_V | F_Z)) | (v & (F_N | F_V)) | ((cpu.a & v) ? 0 : F_Z)); } CYCLES(4); break;  /* BIT abs */
    case 0x2D: a_and(rd(abs_())); CYCLES(4); break;  /* AND abs */
    case 0x2E: { uint16_t e = abs_(); wr(e, rol(rd(e))); } CYCLES(6); break;  /* ROL abs */
    case 0x2F: { uint16_t e = abs_(); uint8_t v = rol(rd(e)); wr(e, v); a_and(v); } CYCLES(6); break;  /* RLA abs */
    case 0x30: CYCLES(branch(cpu.p & F_N)); break;  /* BMI rel */
    case 0x31: a_and(rd(iny())); CYCLES(5 + page); break;  /* AND iny */
    case 0x32: CYCLES(2); break;  /* illegal -> NOP */
    case 0x33: { uint16_t e = iny(); uint8_t v = rol(rd(e)); wr(e, v); a_and(v); } CYCLES(6); break;  /* RLA iny */
    case 0x34: CYCLES(2); break;  /* illegal -> NOP */
    case 0x35: a_and(rd(zpx())); CYCLES(4); break;  /* AND zpx */
    case 0x36: { uint16_t e = zpx(); wr(e, rol(rd(e))); } CYCLES(6); break;  /* ROL zpx */
    case 0x37: { uint16_t e = zpx(); uint8_t v = rol(rd(e)); wr(e, v); a_and(v); } CYCLES(6); break;  /* RLA zpx */
    case 0x38: cpu.p |= F_C; CYCLES(2); break;  /* SEC */
    case 0x39: a_and(rd(aby())); CYCLES(4 + page); break;  /* AND aby */
    case 0x3A: CYCLES(2); break;  /* illegal -> NOP */
    case 0x3B: { uint16_t e = aby(); uint8_t v = rol(rd(e)); wr(e, v); a_and(v); } CYCLES(7); break;  /* RLA aby */
    case 0x3C: CYCLES(2); break;  /* illegal -> NOP */
    case 0x3D: a_and(rd(abx())); CYCLES(4 + page); break;  /* AND abx */
    case 0x3E: { uint16_t e = abx(); wr(e, rol(rd(e))); } CYCLES(7); break;  /* ROL abx */
    case 0x3F: { uint16_t e = abx(); uint8_t v = rol(rd(e)); wr(e, v); a_and(v); } CYCLES(7); break;  /* RLA abx */
    case 0x40: rti(); CYCLES(6); break;  /* RTI */
    case 0x41: a_eor(rd(inx())); CYCLES(6); break;  /* EOR inx */
    case 0x42: CYCLES(2); break;  /* illegal -> NOP */
    case 0x43: { uint16_t e = inx(); uint8_t v = lsr(rd(e)); wr(e, v); a_eor(v); } CYCLES(6); break;  /* SRE inx */
    case 0x44: CYCLES(2); break;  /* illegal -> NOP */
    case 0x45: a_eor(rd(zp())); CYCLES(3); break;  /* EOR zp */
    case 0x46: { uint16_t e = zp(); wr(e, lsr(rd(e))); } CYCLES(5); break;  /* LSR zp */
    case 0x47: { uint16_t e = zp(); uint8_t v = lsr(rd(e)); wr(e, v); a_eor(v); } CYCLES(5); break;  /* SRE zp */
    case 0x48: push(cpu.a); CYCLES(3); break;  /* PHA */
    case 0x49: a_eor(rd(imm())); CYCLES(2); break;  /* EOR imm */
    case 0x4A: cpu.a = lsr(cpu.a); CYCLES(2); break;  /* LSR A */
    case 0x4B: CYCLES(2); break;  /* illegal -> NOP */
    case 0x4C: cpu.pc = abs_(); CYCLES(3); break;  /* JMP abs */
    case 0x4D: a_eor(rd(abs_())); CYCLES(4); break;  /* EOR abs */
    case 0x4E: { uint16_t e = abs_(); wr(e, lsr(rd(e))); } CYCLES(6); break;  /* LSR abs */
    case 0x4F: { uint16_t e = abs_(); uint8_t v = lsr(rd(e)); wr(e, v); a_eor(v); } CYCLES(6); break;  /* SRE abs */
    case 0x50: CYCLES(branch(!(cpu.p & F_V))); break;  /* BVC rel */
    case 0x51: a_eor(rd(iny())); CYCLES(5 + page); break;  /* EOR iny */
    case 0x52: CYCLES(2); break;  /* illegal -> NOP */
    case 0x53: { uint16_t e = iny(); uint8_t v = lsr(rd(e)); wr(e, v); a_eor(v); } CYCLES(6); break;  /* SRE iny */
    case 0x54: CYCLES(2); break;  /* illegal -> NOP */
    case 0x55: a_eor(rd(zpx())); CYCLES(4); break;  /* EOR zpx */
    case 0x56: { uint16_t e = zpx(); wr(e, lsr(rd(e))); } CYCLES(6); break;  /* LSR zpx */
    case 0x57: { uint16_t e = zpx(); uint8_t v = lsr(rd(e)); wr(e, v); a_eor(v); } CYCLES(6); break;  /* SRE zpx */
    case 0x58: cpu.p &= (uint8_t)~F_I; CYCLES(2); break;  /* CLI */
    case 0x59: a_eor(rd(aby())); CYCLES(4 + page); break;  /* EOR aby */
    case 0x5A: CYCLES(2); break;  /* illegal -> NOP */
    case 0x5B: { uint16_t e = aby(); uint8_t v = lsr(rd(e)); wr(e, v); a_eor(v); } CYCLES(7); break;  /* SRE aby */
    case 0x5C: CYCLES(2); break;  /* illegal -> NOP */
    case 0x5D: a_eor(rd(abx())); CYCLES(4 + page); break;  /* EOR abx */
    case 0x5E: { uint16_t e = abx(); wr(e, lsr(rd(e))); } CYCLES(7); break;  /* LSR abx */
    case 0x5F: { uint16_t e = abx(); uint8_t v = lsr(rd(e)); wr(e, v); a_eor(v); } CYCLES(7); break;  /* SRE abx */
    case 0x60: rts(); CYCLES(6); break;  /* RTS */
    case 0x61: a_adc(rd(inx())); CYCLES(6); break;  /* ADC inx */
    case 0x62: CYCLES(2); break;  /* illegal -> NOP */
    case 0x63: { uint16_t e = inx(); uint8_t v = ror(rd(e)); wr(e, v); a_adc(v); } CYCLES(6); break;  /* RRA inx */
    case 0x64: CYCLES(2); break;  /* illegal -> NOP */
    case 0x65: a_adc(rd(zp())); CYCLES(3); break;  /* ADC zp */
    case 0x66: { uint16_t e = zp(); wr(e, ror(rd(e))); } CYCLES(5); break;  /* ROR zp */
    case 0x67: { uint16_t e = zp(); uint8_t v = ror(rd(e)); wr(e, v); a_adc(v); } CYCLES(5); break;  /* RRA zp */
    case 0x68: cpu.a = pull(); setzn(cpu.a); CYCLES(4); break;  /* PLA */
    case 0x69: a_adc(rd(imm())); CYCLES(2); break;  /* ADC imm */
    case 0x6A: cpu.a = ror(cpu.a); CYCLES(2); break;  /* ROR A */
    case 0x6B: CYCLES(2); break;  /* illegal -> NOP */
    case 0x6C: jmp_ind(); CYCLES(5); break;  /* JMP (ind) */
    case 0x6D: a_adc(rd(abs_())); CYCLES(4); break;  /* ADC abs */
    case 0x6E: { uint16_t e = abs_(); wr(e, ror(rd(e))); } CYCLES(6); break;  /* ROR abs */
    case 0x6F: { uint16_t e = abs_(); uint8_t v = ror(rd(e)); wr(e, v); a_adc(v); } CYCLES(6); break;  /* RRA abs */
    case 0x70: CYCLES(branch(cpu.p & F_V)); break;  /* BVS rel */
    case 0x71: a_adc(rd(iny())); CYCLES(5 + page); break;  /* ADC iny */
    case 0x72: CYCLES(2); break;  /* illegal -> NOP */
    case 0x73: { uint16_t e = iny(); uint8_t v = ror(rd(e)); wr(e, v); a_adc(v); } CYCLES(6); break;  /* RRA iny */
    case 0x74: CYCLES(2); break;  /* illegal -> NOP */
    case 0x75: a_adc(rd(zpx())); CYCLES(4); break;  /* ADC zpx */
    case 0x76: { uint16_t e = zpx(); wr(e, ror(rd(e))); } CYCLES(6); break;  /* ROR zpx */
    case 0x77: { uint16_t e = zpx(); uint8_t v = ror(rd(e)); wr(e, v); a_adc(v); } CYCLES(6); break;  /* RRA zpx */
    case 0x78: cpu.p |= F_I; CYCLES(2); break;  /* SEI */
    case 0x79: a_adc(rd(aby())); CYCLES(4 + page); break;  /* ADC aby */
    case 0x7A: CYCLES(2); break;  /* illegal -> NOP */
    case 0x7B: { uint16_t e = aby(); uint8_t v = ror(rd(e)); wr(e, v); a_adc(v); } CYCLES(7); break;  /* RRA aby */
    case 0x7C: CYCLES(2); break;  /* illegal -> NOP */
    case 0x7D: a_adc(rd(abx())); CYCLES(4 + page); break;  /* ADC abx */
    case 0x7E: { uint16_t e = abx(); wr(e, ror(rd(e))); } CYCLES(7); break;  /* ROR abx */
    case 0x7F: { uint16_t e = abx(); uint8_t v = ror(rd(e)); wr(e, v); a_adc(v); } CYCLES(7); break;  /* RRA abx */
    case 0x80: CYCLES(2); break;  /* illegal -> NOP */
    case 0x81: wr(inx(), cpu.a); CYCLES(6); break;  /* STA inx */
    case 0x82: CYCLES(2); break;  /* illegal -> NOP */
    case 0x83: wr(inx(), (uint8_t)(cpu.a & cpu.x)); CYCLES(6); break;  /* SAX inx */
    case 0x84: wr(zp(), cpu.y); CYCLES(3); break;  /* STY zp */
    case 0x85: wr(zp(), cpu.a); CYCLES(3); break;  /* STA zp */
    case 0x86: wr(zp(), cpu.x); CYCLES(3); break;  /* STX zp */
    case 0x87: wr(zp(), (uint8_t)(cpu.a & cpu.x)); CYCLES(3); break;  /* SAX zp */
    case 0x88: cpu.y--; setzn(cpu.y); CYCLES(2); break;  /* DEY */
    case 0x89: CYCLES(2); break;  /* illegal -> NOP */
    case 0x8A: cpu.a = cpu.x; setzn(cpu.a); CYCLES(2); break;  /* TXA */
    case 0x8B: CYCLES(2); break;  /* illegal -> NOP */
    case 0x8C: wr(abs_(), cpu.y); CYCLES(4); break;  /* STY abs */
    case 0x8D: wr(abs_(), cpu.a); CYCLES(4); break;  /* STA abs */
    case 0x8E: wr(abs_(), cpu.x); CYCLES(4); break;  /* STX abs */
    case 0x8F: wr(abs_(), (uint8_t)(cpu.a & cpu.x)); CYCLES(4); break;  /* SAX abs */
    case 0x90: CYCLES(branch(!(cpu.p & F_C))); break;  /* BCC rel */
    case 0x91: wr(iny(), cpu.a); CYCLES(6); break;  /* STA iny */
    case 0x92: CYCLES(2); break;  /* illegal -> NOP */
    case 0x93: CYCLES(2); break;  /* illegal -> NOP */
    case 0x94: wr(zpx(), cpu.y); CYCLES(4); break;  /* STY zpx */
    case 0x95: wr(zpx(), cpu.a); CYCLES(4); break;  /* STA zpx */
    case 0x96: wr(zpy(), cpu.x); CYCLES(4); break;  /* STX zpy */
    case 0x97: wr(zpy(), (uint8_t)(cpu.a & cpu.x)); CYCLES(4); break;  /* SAX zpy */
    case 0x98: cpu.a = cpu.y; setzn(cpu.a); CYCLES(2); break;  /* TYA */
    case 0x99: wr(aby(), cpu.a); CYCLES(5); break;  /* STA aby */
    case 0x9A: cpu.sp = cpu.x; CYCLES(2); break;  /* TXS */
    case 0x9B: CYCLES(2); break;  /* illegal -> NOP */
    case 0x9C: CYCLES(2); break;  /* illegal -> NOP */
    case 0x9D: wr(abx(), cpu.a); CYCLES(5); break;  /* STA abx */
    case 0x9E: CYCLES(2); break;  /* illegal -> NOP */
    case 0x9F: CYCLES(2); break;  /* illegal -> NOP */
    case 0xA0: cpu.y = rd(imm()); setzn(cpu.y); CYCLES(2); break;  /* LDY imm */
    case 0xA1: cpu.a = rd(inx()); setzn(cpu.a); CYCLES(6); break;  /* LDA inx */
    case 0xA2: cpu.x = rd(imm()); setzn(cpu.x); CYCLES(2); break;  /* LDX imm */
    case 0xA3: { uint8_t v = rd(inx()); cpu.a = v; cpu.x = v; setzn(v); } CYCLES(6); break;
    case 0xA4: cpu.y = rd(zp()); setzn(cpu.y); CYCLES(3); break;  /* LDY zp */
    case 0xA5: cpu.a = rd(zp()); setzn(cpu.a); CYCLES(3); break;  /* LDA zp */
    case 0xA6: cpu.x = rd(zp()); setzn(cpu.x); CYCLES(3); break;  /* LDX zp */
    case 0xA7: { uint8_t v = rd(zp()); cpu.a = v; cpu.x = v; setzn(v); } CYCLES(3); break;
    case 0xA8: cpu.y = cpu.a; setzn(cpu.y); CYCLES(2); break;  /* TAY */
    case 0xA9: cpu.a = rd(imm()); setzn(cpu.a); CYCLES(2); break;  /* LDA imm */
    case 0xAA: cpu.x = cpu.a; setzn(cpu.x); CYCLES(2); break;  /* TAX */
    case 0xAB: CYCLES(2); break;  /* illegal -> NOP */
    case 0xAC: cpu.y = rd(abs_()); setzn(cpu.y); CYCLES(4); break;  /* LDY abs */
    case 0xAD: cpu.a = rd(abs_()); setzn(cpu.a); CYCLES(4); break;  /* LDA abs */
    case 0xAE: cpu.x = rd(abs_()); setzn(cpu.x); CYCLES(4); break;  /* LDX abs */
    case 0xAF: { uint8_t v = rd(abs_()); cpu.a = v; cpu.x = v; setzn(v); } CYCLES(4); break;
    case 0xB0: CYCLES(branch(cpu.p & F_C)); break;  /* BCS rel */
    case 0xB1: cpu.a = rd(iny()); setzn(cpu.a); CYCLES(5 + page); break;  /* LDA iny */
    case 0xB2: CYCLES(2); break;  /* illegal -> NOP */
    case 0xB3: { uint8_t v = rd(iny()); cpu.a = v; cpu.x = v; setzn(v); } CYCLES(5 + page); break;
    case 0xB4: cpu.y = rd(zpx()); setzn(cpu.y); CYCLES(4); break;  /* LDY zpx */
    case 0xB5: cpu.a = rd(zpx()); setzn(cpu.a); CYCLES(4); break;  /* LDA zpx */
    case 0xB6: cpu.x = rd(zpy()); setzn(cpu.x); CYCLES(4); break;  /* LDX zpy */
    case 0xB7: { uint8_t v = rd(zpy()); cpu.a = v; cpu.x = v; setzn(v); } CYCLES(4); break;
    case 0xB8: cpu.p &= (uint8_t)~F_V; CYCLES(2); break;  /* CLV */
    case 0xB9: cpu.a = rd(aby()); setzn(cpu.a); CYCLES(4 + page); break;  /* LDA aby */
    case 0xBA: cpu.x = cpu.sp; setzn(cpu.x); CYCLES(2); break;  /* TSX */
    case 0xBB: CYCLES(2); break;  /* illegal -> NOP */
    case 0xBC: cpu.y = rd(abx()); setzn(cpu.y); CYCLES(4 + page); break;  /* LDY abx */
    case 0xBD: cpu.a = rd(abx()); setzn(cpu.a); CYCLES(4 + page); break;  /* LDA abx */
    case 0xBE: cpu.x = rd(aby()); setzn(cpu.x); CYCLES(4 + page); break;  /* LDX aby */
    case 0xBF: { uint8_t v = rd(aby()); cpu.a = v; cpu.x = v; setzn(v); } CYCLES(4 + page); break;
    case 0xC0: a_cpy(rd(imm())); CYCLES(2); break;  /* CPY imm */
    case 0xC1: a_cmp(rd(inx())); CYCLES(6); break;  /* CMP inx */
    case 0xC2: CYCLES(2); break;  /* illegal -> NOP */
    case 0xC3: { uint16_t e = inx(); uint8_t v = dec8(rd(e)); wr(e, v); a_cmp(v); } CYCLES(6); break;  /* DCP inx */
    case 0xC4: a_cpy(rd(zp())); CYCLES(3); break;  /* CPY zp */
    case 0xC5: a_cmp(rd(zp())); CYCLES(3); break;  /* CMP zp */
    case 0xC6: { uint16_t e = zp(); wr(e, dec8(rd(e))); } CYCLES(5); break;  /* DEC zp */
    case 0xC7: { uint16_t e = zp(); uint8_t v = dec8(rd(e)); wr(e, v); a_cmp(v); } CYCLES(5); break;  /* DCP zp */
    case 0xC8: cpu.y++; setzn(cpu.y); CYCLES(2); break;  /* INY */
    case 0xC9: a_cmp(rd(imm())); CYCLES(2); break;  /* CMP imm */
    case 0xCA: cpu.x--; setzn(cpu.x); CYCLES(2); break;  /* DEX */
    case 0xCB: CYCLES(2); break;  /* illegal -> NOP */
    case 0xCC: a_cpy(rd(abs_())); CYCLES(4); break;  /* CPY abs */
    case 0xCD: a_cmp(rd(abs_())); CYCLES(4); break;  /* CMP abs */
    case 0xCE: { uint16_t e = abs_(); wr(e, dec8(rd(e))); } CYCLES(6); break;  /* DEC abs */
    case 0xCF: { uint16_t e = abs_(); uint8_t v = dec8(rd(e)); wr(e, v); a_cmp(v); } CYCLES(6); break;  /* DCP abs */
    case 0xD0: CYCLES(branch(!(cpu.p & F_Z))); break;  /* BNE rel */
    case 0xD1: a_cmp(rd(iny())); CYCLES(5 + page); break;  /* CMP iny */
    case 0xD2: CYCLES(2); break;  /* illegal -> NOP */
    case 0xD3: { uint16_t e = iny(); uint8_t v = dec8(rd(e)); wr(e, v); a_cmp(v); } CYCLES(6); break;  /* DCP iny */
    case 0xD4: CYCLES(2); break;  /* illegal -> NOP */
    case 0xD5: a_cmp(rd(zpx())); CYCLES(4); break;  /* CMP zpx */
    case 0xD6: { uint16_t e = zpx(); wr(e, dec8(rd(e))); } CYCLES(6); break;  /* DEC zpx */
    case 0xD7: { uint16_t e = zpx(); uint8_t v = dec8(rd(e)); wr(e, v); a_cmp(v); } CYCLES(6); break;  /* DCP zpx */
    case 0xD8: cpu.p &= (uint8_t)~F_D; CYCLES(2); break;  /* CLD */
    case 0xD9: a_cmp(rd(aby())); CYCLES(4 + page); break;  /* CMP aby */
    case 0xDA: CYCLES(2); break;  /* illegal -> NOP */
    case 0xDB: { uint16_t e = aby(); uint8_t v = dec8(rd(e)); wr(e, v); a_cmp(v); } CYCLES(7); break;  /* DCP aby */
    case 0xDC: CYCLES(2); break;  /* illegal -> NOP */
    case 0xDD: a_cmp(rd(abx())); CYCLES(4 + page); break;  /* CMP abx */
    case 0xDE: { uint16_t e = abx(); wr(e, dec8(rd(e))); } CYCLES(7); break;  /* DEC abx */
    case 0xDF: { uint16_t e = abx(); uint8_t v = dec8(rd(e)); wr(e, v); a_cmp(v); } CYCLES(7); break;  /* DCP abx */
    case 0xE0: a_cpx(rd(imm())); CYCLES(2); break;  /* CPX imm */
    case 0xE1: a_sbc(rd(inx())); CYCLES(6); break;  /* SBC inx */
    case 0xE2: CYCLES(2); break;  /* illegal -> NOP */
    case 0xE3: { uint16_t e = inx(); uint8_t v = inc8(rd(e)); wr(e, v); a_sbc(v); } CYCLES(6); break;  /* ISC inx */
    case 0xE4: a_cpx(rd(zp())); CYCLES(3); break;  /* CPX zp */
    case 0xE5: a_sbc(rd(zp())); CYCLES(3); break;  /* SBC zp */
    case 0xE6: { uint16_t e = zp(); wr(e, inc8(rd(e))); } CYCLES(5); break;  /* INC zp */
    case 0xE7: { uint16_t e = zp(); uint8_t v = inc8(rd(e)); wr(e, v); a_sbc(v); } CYCLES(5); break;  /* ISC zp */
    case 0xE8: cpu.x++; setzn(cpu.x); CYCLES(2); break;  /* INX */
    case 0xE9: a_sbc(rd(imm())); CYCLES(2); break;  /* SBC imm */
    case 0xEA: CYCLES(2); break;  /* NOP */
    case 0xEB: CYCLES(2); break;  /* illegal -> NOP */
    case 0xEC: a_cpx(rd(abs_())); CYCLES(4); break;  /* CPX abs */
    case 0xED: a_sbc(rd(abs_())); CYCLES(4); break;  /* SBC abs */
    case 0xEE: { uint16_t e = abs_(); wr(e, inc8(rd(e))); } CYCLES(6); break;  /* INC abs */
    case 0xEF: { uint16_t e = abs_(); uint8_t v = inc8(rd(e)); wr(e, v); a_sbc(v); } CYCLES(6); break;  /* ISC abs */
    case 0xF0: CYCLES(branch(cpu.p & F_Z)); break;  /* BEQ rel */
    case 0xF1: a_sbc(rd(iny())); CYCLES(5 + page); break;  /* SBC iny */
    case 0xF2: CYCLES(2); break;  /* illegal -> NOP */
    case 0xF3: { uint16_t e = iny(); uint8_t v = inc8(rd(e)); wr(e, v); a_sbc(v); } CYCLES(6); break;  /* ISC iny */
    case 0xF4: CYCLES(2); break;  /* illegal -> NOP */
    case 0xF5: a_sbc(rd(zpx())); CYCLES(4); break;  /* SBC zpx */
    case 0xF6: { uint16_t e = zpx(); wr(e, inc8(rd(e))); } CYCLES(6); break;  /* INC zpx */
    case 0xF7: { uint16_t e = zpx(); uint8_t v = inc8(rd(e)); wr(e, v); a_sbc(v); } CYCLES(6); break;  /* ISC zpx */
    case 0xF8: cpu.p |= F_D; CYCLES(2); break;  /* SED */
    case 0xF9: a_sbc(rd(aby())); CYCLES(4 + page); break;  /* SBC aby */
    case 0xFA: CYCLES(2); break;  /* illegal -> NOP */
    case 0xFB: { uint16_t e = aby(); uint8_t v = inc8(rd(e)); wr(e, v); a_sbc(v); } CYCLES(7); break;  /* ISC aby */
    case 0xFC: CYCLES(2); break;  /* illegal -> NOP */
    case 0xFD: a_sbc(rd(abx())); CYCLES(4 + page); break;  /* SBC abx */
    case 0xFE: { uint16_t e = abx(); wr(e, inc8(rd(e))); } CYCLES(7); break;  /* INC abx */
    case 0xFF: { uint16_t e = abx(); uint8_t v = inc8(rd(e)); wr(e, v); a_sbc(v); } CYCLES(7); break;  /* ISC abx */
