/* GENERATED by tools/gen_6502.py — do not edit by hand. */
/*
 * The instruction loop of cpu_run(), split into one case per opcode.
 * Every case is written in the macros cpu6502.c defines over the
 * automatic variables of that function — FETCH8()/RD()/WR(),
 * IMM()/ZP()/ABX()/..., A_ORA()/A_ADC()/SETZN()/..., CYCLES(),
 * PUSH()/PULL()/BRANCH_TAKE()/JMP_IND() — so the registers stay
 * locals of the loop and the compiler can hold them in host
 * registers; that is why the generator emits the loop itself and
 * not only the case labels (a #include cannot sit in a macro).
 *
 * Operand macros appear exactly once per case, in the order the old
 * function-call form evaluated them, so nothing with a side effect
 * (INX(), RD(), PULL()) is evaluated twice. `page` is set by the
 * addressing macro and read by CYCLES(n + page) in the same case.
 */

    while (done < budget) {
        cyc = 0;
        page = 0;
        switch (FETCH8()) {
        case 0x00: BRK(); CYCLES(7); break;  /* BRK */
        case 0x01: { uint8_t v = RD(INX()); A_ORA(v); } CYCLES(6); break;  /* ORA inx */
        case 0x02: CYCLES(2); break;  /* illegal -> NOP */
        case 0x03: { uint16_t e = INX(); uint8_t v = ASL(RD(e)); WR(e, v); A_ORA(v); } CYCLES(6); break;  /* SLO inx */
        case 0x04: CYCLES(2); break;  /* illegal -> NOP */
        case 0x05: { uint8_t v = RD(ZP()); A_ORA(v); } CYCLES(3); break;  /* ORA zp */
        case 0x06: { uint16_t e = ZP(); WR(e, ASL(RD(e))); } CYCLES(5); break;  /* ASL zp */
        case 0x07: { uint16_t e = ZP(); uint8_t v = ASL(RD(e)); WR(e, v); A_ORA(v); } CYCLES(5); break;  /* SLO zp */
        case 0x08: PUSH((uint8_t)(p | F_B | F_U)); CYCLES(3); break;  /* PHP */
        case 0x09: { uint8_t v = RD(IMM()); A_ORA(v); } CYCLES(2); break;  /* ORA imm */
        case 0x0A: a = ASL(a); CYCLES(2); break;  /* ASL A */
        case 0x0B: CYCLES(2); break;  /* illegal -> NOP */
        case 0x0C: CYCLES(2); break;  /* illegal -> NOP */
        case 0x0D: { uint8_t v = RD(ABS_()); A_ORA(v); } CYCLES(4); break;  /* ORA abs */
        case 0x0E: { uint16_t e = ABS_(); WR(e, ASL(RD(e))); } CYCLES(6); break;  /* ASL abs */
        case 0x0F: { uint16_t e = ABS_(); uint8_t v = ASL(RD(e)); WR(e, v); A_ORA(v); } CYCLES(6); break;  /* SLO abs */
        case 0x10: BRANCH_TAKE(!(p & F_N)); break;  /* BPL rel */
        case 0x11: { uint8_t v = RD(INY()); A_ORA(v); } CYCLES(5 + page); break;  /* ORA iny */
        case 0x12: CYCLES(2); break;  /* illegal -> NOP */
        case 0x13: { uint16_t e = INY(); uint8_t v = ASL(RD(e)); WR(e, v); A_ORA(v); } CYCLES(6); break;  /* SLO iny */
        case 0x14: CYCLES(2); break;  /* illegal -> NOP */
        case 0x15: { uint8_t v = RD(ZPX()); A_ORA(v); } CYCLES(4); break;  /* ORA zpx */
        case 0x16: { uint16_t e = ZPX(); WR(e, ASL(RD(e))); } CYCLES(6); break;  /* ASL zpx */
        case 0x17: { uint16_t e = ZPX(); uint8_t v = ASL(RD(e)); WR(e, v); A_ORA(v); } CYCLES(6); break;  /* SLO zpx */
        case 0x18: p &= (uint8_t)~F_C; CYCLES(2); break;  /* CLC */
        case 0x19: { uint8_t v = RD(ABY()); A_ORA(v); } CYCLES(4 + page); break;  /* ORA aby */
        case 0x1A: CYCLES(2); break;  /* illegal -> NOP */
        case 0x1B: { uint16_t e = ABY(); uint8_t v = ASL(RD(e)); WR(e, v); A_ORA(v); } CYCLES(7); break;  /* SLO aby */
        case 0x1C: CYCLES(2); break;  /* illegal -> NOP */
        case 0x1D: { uint8_t v = RD(ABX()); A_ORA(v); } CYCLES(4 + page); break;  /* ORA abx */
        case 0x1E: { uint16_t e = ABX(); WR(e, ASL(RD(e))); } CYCLES(7); break;  /* ASL abx */
        case 0x1F: { uint16_t e = ABX(); uint8_t v = ASL(RD(e)); WR(e, v); A_ORA(v); } CYCLES(7); break;  /* SLO abx */
        case 0x20: { uint16_t t = ABS_(); PUSH16((uint16_t)(pc - 1)); pc = t; CYCLES(6); } break;  /* JSR abs */
        case 0x21: { uint8_t v = RD(INX()); A_AND(v); } CYCLES(6); break;  /* AND inx */
        case 0x22: CYCLES(2); break;  /* illegal -> NOP */
        case 0x23: { uint16_t e = INX(); uint8_t v = ROL(RD(e)); WR(e, v); A_AND(v); } CYCLES(6); break;  /* RLA inx */
        case 0x24: { uint8_t v = RD(ZP()); p = (uint8_t)((p & ~(F_N | F_V | F_Z)) | (v & (F_N | F_V)) | ((a & v) ? 0 : F_Z)); } CYCLES(3); break;  /* BIT zp */
        case 0x25: { uint8_t v = RD(ZP()); A_AND(v); } CYCLES(3); break;  /* AND zp */
        case 0x26: { uint16_t e = ZP(); WR(e, ROL(RD(e))); } CYCLES(5); break;  /* ROL zp */
        case 0x27: { uint16_t e = ZP(); uint8_t v = ROL(RD(e)); WR(e, v); A_AND(v); } CYCLES(5); break;  /* RLA zp */
        case 0x28: p = (uint8_t)((PULL() & (uint8_t)~F_B) | F_U); CYCLES(4); break;  /* PLP */
        case 0x29: { uint8_t v = RD(IMM()); A_AND(v); } CYCLES(2); break;  /* AND imm */
        case 0x2A: a = ROL(a); CYCLES(2); break;  /* ROL A */
        case 0x2B: CYCLES(2); break;  /* illegal -> NOP */
        case 0x2C: { uint8_t v = RD(ABS_()); p = (uint8_t)((p & ~(F_N | F_V | F_Z)) | (v & (F_N | F_V)) | ((a & v) ? 0 : F_Z)); } CYCLES(4); break;  /* BIT abs */
        case 0x2D: { uint8_t v = RD(ABS_()); A_AND(v); } CYCLES(4); break;  /* AND abs */
        case 0x2E: { uint16_t e = ABS_(); WR(e, ROL(RD(e))); } CYCLES(6); break;  /* ROL abs */
        case 0x2F: { uint16_t e = ABS_(); uint8_t v = ROL(RD(e)); WR(e, v); A_AND(v); } CYCLES(6); break;  /* RLA abs */
        case 0x30: BRANCH_TAKE(p & F_N); break;  /* BMI rel */
        case 0x31: { uint8_t v = RD(INY()); A_AND(v); } CYCLES(5 + page); break;  /* AND iny */
        case 0x32: CYCLES(2); break;  /* illegal -> NOP */
        case 0x33: { uint16_t e = INY(); uint8_t v = ROL(RD(e)); WR(e, v); A_AND(v); } CYCLES(6); break;  /* RLA iny */
        case 0x34: CYCLES(2); break;  /* illegal -> NOP */
        case 0x35: { uint8_t v = RD(ZPX()); A_AND(v); } CYCLES(4); break;  /* AND zpx */
        case 0x36: { uint16_t e = ZPX(); WR(e, ROL(RD(e))); } CYCLES(6); break;  /* ROL zpx */
        case 0x37: { uint16_t e = ZPX(); uint8_t v = ROL(RD(e)); WR(e, v); A_AND(v); } CYCLES(6); break;  /* RLA zpx */
        case 0x38: p |= F_C; CYCLES(2); break;  /* SEC */
        case 0x39: { uint8_t v = RD(ABY()); A_AND(v); } CYCLES(4 + page); break;  /* AND aby */
        case 0x3A: CYCLES(2); break;  /* illegal -> NOP */
        case 0x3B: { uint16_t e = ABY(); uint8_t v = ROL(RD(e)); WR(e, v); A_AND(v); } CYCLES(7); break;  /* RLA aby */
        case 0x3C: CYCLES(2); break;  /* illegal -> NOP */
        case 0x3D: { uint8_t v = RD(ABX()); A_AND(v); } CYCLES(4 + page); break;  /* AND abx */
        case 0x3E: { uint16_t e = ABX(); WR(e, ROL(RD(e))); } CYCLES(7); break;  /* ROL abx */
        case 0x3F: { uint16_t e = ABX(); uint8_t v = ROL(RD(e)); WR(e, v); A_AND(v); } CYCLES(7); break;  /* RLA abx */
        case 0x40: RTI(); CYCLES(6); break;  /* RTI */
        case 0x41: { uint8_t v = RD(INX()); A_EOR(v); } CYCLES(6); break;  /* EOR inx */
        case 0x42: CYCLES(2); break;  /* illegal -> NOP */
        case 0x43: { uint16_t e = INX(); uint8_t v = LSR(RD(e)); WR(e, v); A_EOR(v); } CYCLES(6); break;  /* SRE inx */
        case 0x44: CYCLES(2); break;  /* illegal -> NOP */
        case 0x45: { uint8_t v = RD(ZP()); A_EOR(v); } CYCLES(3); break;  /* EOR zp */
        case 0x46: { uint16_t e = ZP(); WR(e, LSR(RD(e))); } CYCLES(5); break;  /* LSR zp */
        case 0x47: { uint16_t e = ZP(); uint8_t v = LSR(RD(e)); WR(e, v); A_EOR(v); } CYCLES(5); break;  /* SRE zp */
        case 0x48: PUSH(a); CYCLES(3); break;  /* PHA */
        case 0x49: { uint8_t v = RD(IMM()); A_EOR(v); } CYCLES(2); break;  /* EOR imm */
        case 0x4A: a = LSR(a); CYCLES(2); break;  /* LSR A */
        case 0x4B: CYCLES(2); break;  /* illegal -> NOP */
        case 0x4C: pc = ABS_(); CYCLES(3); break;  /* JMP abs */
        case 0x4D: { uint8_t v = RD(ABS_()); A_EOR(v); } CYCLES(4); break;  /* EOR abs */
        case 0x4E: { uint16_t e = ABS_(); WR(e, LSR(RD(e))); } CYCLES(6); break;  /* LSR abs */
        case 0x4F: { uint16_t e = ABS_(); uint8_t v = LSR(RD(e)); WR(e, v); A_EOR(v); } CYCLES(6); break;  /* SRE abs */
        case 0x50: BRANCH_TAKE(!(p & F_V)); break;  /* BVC rel */
        case 0x51: { uint8_t v = RD(INY()); A_EOR(v); } CYCLES(5 + page); break;  /* EOR iny */
        case 0x52: CYCLES(2); break;  /* illegal -> NOP */
        case 0x53: { uint16_t e = INY(); uint8_t v = LSR(RD(e)); WR(e, v); A_EOR(v); } CYCLES(6); break;  /* SRE iny */
        case 0x54: CYCLES(2); break;  /* illegal -> NOP */
        case 0x55: { uint8_t v = RD(ZPX()); A_EOR(v); } CYCLES(4); break;  /* EOR zpx */
        case 0x56: { uint16_t e = ZPX(); WR(e, LSR(RD(e))); } CYCLES(6); break;  /* LSR zpx */
        case 0x57: { uint16_t e = ZPX(); uint8_t v = LSR(RD(e)); WR(e, v); A_EOR(v); } CYCLES(6); break;  /* SRE zpx */
        case 0x58: p &= (uint8_t)~F_I; CYCLES(2); break;  /* CLI */
        case 0x59: { uint8_t v = RD(ABY()); A_EOR(v); } CYCLES(4 + page); break;  /* EOR aby */
        case 0x5A: CYCLES(2); break;  /* illegal -> NOP */
        case 0x5B: { uint16_t e = ABY(); uint8_t v = LSR(RD(e)); WR(e, v); A_EOR(v); } CYCLES(7); break;  /* SRE aby */
        case 0x5C: CYCLES(2); break;  /* illegal -> NOP */
        case 0x5D: { uint8_t v = RD(ABX()); A_EOR(v); } CYCLES(4 + page); break;  /* EOR abx */
        case 0x5E: { uint16_t e = ABX(); WR(e, LSR(RD(e))); } CYCLES(7); break;  /* LSR abx */
        case 0x5F: { uint16_t e = ABX(); uint8_t v = LSR(RD(e)); WR(e, v); A_EOR(v); } CYCLES(7); break;  /* SRE abx */
        case 0x60: RTS(); CYCLES(6); break;  /* RTS */
        case 0x61: { uint8_t v = RD(INX()); A_ADC(v); } CYCLES(6); break;  /* ADC inx */
        case 0x62: CYCLES(2); break;  /* illegal -> NOP */
        case 0x63: { uint16_t e = INX(); uint8_t v = ROR(RD(e)); WR(e, v); A_ADC(v); } CYCLES(6); break;  /* RRA inx */
        case 0x64: CYCLES(2); break;  /* illegal -> NOP */
        case 0x65: { uint8_t v = RD(ZP()); A_ADC(v); } CYCLES(3); break;  /* ADC zp */
        case 0x66: { uint16_t e = ZP(); WR(e, ROR(RD(e))); } CYCLES(5); break;  /* ROR zp */
        case 0x67: { uint16_t e = ZP(); uint8_t v = ROR(RD(e)); WR(e, v); A_ADC(v); } CYCLES(5); break;  /* RRA zp */
        case 0x68: a = PULL(); SETZN(a); CYCLES(4); break;  /* PLA */
        case 0x69: { uint8_t v = RD(IMM()); A_ADC(v); } CYCLES(2); break;  /* ADC imm */
        case 0x6A: a = ROR(a); CYCLES(2); break;  /* ROR A */
        case 0x6B: CYCLES(2); break;  /* illegal -> NOP */
        case 0x6C: JMP_IND(); CYCLES(5); break;  /* JMP (ind) */
        case 0x6D: { uint8_t v = RD(ABS_()); A_ADC(v); } CYCLES(4); break;  /* ADC abs */
        case 0x6E: { uint16_t e = ABS_(); WR(e, ROR(RD(e))); } CYCLES(6); break;  /* ROR abs */
        case 0x6F: { uint16_t e = ABS_(); uint8_t v = ROR(RD(e)); WR(e, v); A_ADC(v); } CYCLES(6); break;  /* RRA abs */
        case 0x70: BRANCH_TAKE(p & F_V); break;  /* BVS rel */
        case 0x71: { uint8_t v = RD(INY()); A_ADC(v); } CYCLES(5 + page); break;  /* ADC iny */
        case 0x72: CYCLES(2); break;  /* illegal -> NOP */
        case 0x73: { uint16_t e = INY(); uint8_t v = ROR(RD(e)); WR(e, v); A_ADC(v); } CYCLES(6); break;  /* RRA iny */
        case 0x74: CYCLES(2); break;  /* illegal -> NOP */
        case 0x75: { uint8_t v = RD(ZPX()); A_ADC(v); } CYCLES(4); break;  /* ADC zpx */
        case 0x76: { uint16_t e = ZPX(); WR(e, ROR(RD(e))); } CYCLES(6); break;  /* ROR zpx */
        case 0x77: { uint16_t e = ZPX(); uint8_t v = ROR(RD(e)); WR(e, v); A_ADC(v); } CYCLES(6); break;  /* RRA zpx */
        case 0x78: p |= F_I; CYCLES(2); break;  /* SEI */
        case 0x79: { uint8_t v = RD(ABY()); A_ADC(v); } CYCLES(4 + page); break;  /* ADC aby */
        case 0x7A: CYCLES(2); break;  /* illegal -> NOP */
        case 0x7B: { uint16_t e = ABY(); uint8_t v = ROR(RD(e)); WR(e, v); A_ADC(v); } CYCLES(7); break;  /* RRA aby */
        case 0x7C: CYCLES(2); break;  /* illegal -> NOP */
        case 0x7D: { uint8_t v = RD(ABX()); A_ADC(v); } CYCLES(4 + page); break;  /* ADC abx */
        case 0x7E: { uint16_t e = ABX(); WR(e, ROR(RD(e))); } CYCLES(7); break;  /* ROR abx */
        case 0x7F: { uint16_t e = ABX(); uint8_t v = ROR(RD(e)); WR(e, v); A_ADC(v); } CYCLES(7); break;  /* RRA abx */
        case 0x80: CYCLES(2); break;  /* illegal -> NOP */
        case 0x81: WR(INX(), a); CYCLES(6); break;  /* STA inx */
        case 0x82: CYCLES(2); break;  /* illegal -> NOP */
        case 0x83: WR(INX(), (uint8_t)(a & x)); CYCLES(6); break;  /* SAX inx */
        case 0x84: WR(ZP(), y); CYCLES(3); break;  /* STY zp */
        case 0x85: WR(ZP(), a); CYCLES(3); break;  /* STA zp */
        case 0x86: WR(ZP(), x); CYCLES(3); break;  /* STX zp */
        case 0x87: WR(ZP(), (uint8_t)(a & x)); CYCLES(3); break;  /* SAX zp */
        case 0x88: y--; SETZN(y); CYCLES(2); break;  /* DEY */
        case 0x89: CYCLES(2); break;  /* illegal -> NOP */
        case 0x8A: a = x; SETZN(a); CYCLES(2); break;  /* TXA */
        case 0x8B: CYCLES(2); break;  /* illegal -> NOP */
        case 0x8C: WR(ABS_(), y); CYCLES(4); break;  /* STY abs */
        case 0x8D: WR(ABS_(), a); CYCLES(4); break;  /* STA abs */
        case 0x8E: WR(ABS_(), x); CYCLES(4); break;  /* STX abs */
        case 0x8F: WR(ABS_(), (uint8_t)(a & x)); CYCLES(4); break;  /* SAX abs */
        case 0x90: BRANCH_TAKE(!(p & F_C)); break;  /* BCC rel */
        case 0x91: WR(INY(), a); CYCLES(6); break;  /* STA iny */
        case 0x92: CYCLES(2); break;  /* illegal -> NOP */
        case 0x93: CYCLES(2); break;  /* illegal -> NOP */
        case 0x94: WR(ZPX(), y); CYCLES(4); break;  /* STY zpx */
        case 0x95: WR(ZPX(), a); CYCLES(4); break;  /* STA zpx */
        case 0x96: WR(ZPY(), x); CYCLES(4); break;  /* STX zpy */
        case 0x97: WR(ZPY(), (uint8_t)(a & x)); CYCLES(4); break;  /* SAX zpy */
        case 0x98: a = y; SETZN(a); CYCLES(2); break;  /* TYA */
        case 0x99: WR(ABY(), a); CYCLES(5); break;  /* STA aby */
        case 0x9A: sp = x; CYCLES(2); break;  /* TXS */
        case 0x9B: CYCLES(2); break;  /* illegal -> NOP */
        case 0x9C: CYCLES(2); break;  /* illegal -> NOP */
        case 0x9D: WR(ABX(), a); CYCLES(5); break;  /* STA abx */
        case 0x9E: CYCLES(2); break;  /* illegal -> NOP */
        case 0x9F: CYCLES(2); break;  /* illegal -> NOP */
        case 0xA0: y = RD(IMM()); SETZN(y); CYCLES(2); break;  /* LDY imm */
        case 0xA1: a = RD(INX()); SETZN(a); CYCLES(6); break;  /* LDA inx */
        case 0xA2: x = RD(IMM()); SETZN(x); CYCLES(2); break;  /* LDX imm */
        case 0xA3: { uint8_t v = RD(INX()); a = v; x = v; SETZN(v); } CYCLES(6); break;
        case 0xA4: y = RD(ZP()); SETZN(y); CYCLES(3); break;  /* LDY zp */
        case 0xA5: a = RD(ZP()); SETZN(a); CYCLES(3); break;  /* LDA zp */
        case 0xA6: x = RD(ZP()); SETZN(x); CYCLES(3); break;  /* LDX zp */
        case 0xA7: { uint8_t v = RD(ZP()); a = v; x = v; SETZN(v); } CYCLES(3); break;
        case 0xA8: y = a; SETZN(y); CYCLES(2); break;  /* TAY */
        case 0xA9: a = RD(IMM()); SETZN(a); CYCLES(2); break;  /* LDA imm */
        case 0xAA: x = a; SETZN(x); CYCLES(2); break;  /* TAX */
        case 0xAB: CYCLES(2); break;  /* illegal -> NOP */
        case 0xAC: y = RD(ABS_()); SETZN(y); CYCLES(4); break;  /* LDY abs */
        case 0xAD: a = RD(ABS_()); SETZN(a); CYCLES(4); break;  /* LDA abs */
        case 0xAE: x = RD(ABS_()); SETZN(x); CYCLES(4); break;  /* LDX abs */
        case 0xAF: { uint8_t v = RD(ABS_()); a = v; x = v; SETZN(v); } CYCLES(4); break;
        case 0xB0: BRANCH_TAKE(p & F_C); break;  /* BCS rel */
        case 0xB1: a = RD(INY()); SETZN(a); CYCLES(5 + page); break;  /* LDA iny */
        case 0xB2: CYCLES(2); break;  /* illegal -> NOP */
        case 0xB3: { uint8_t v = RD(INY()); a = v; x = v; SETZN(v); } CYCLES(5 + page); break;
        case 0xB4: y = RD(ZPX()); SETZN(y); CYCLES(4); break;  /* LDY zpx */
        case 0xB5: a = RD(ZPX()); SETZN(a); CYCLES(4); break;  /* LDA zpx */
        case 0xB6: x = RD(ZPY()); SETZN(x); CYCLES(4); break;  /* LDX zpy */
        case 0xB7: { uint8_t v = RD(ZPY()); a = v; x = v; SETZN(v); } CYCLES(4); break;
        case 0xB8: p &= (uint8_t)~F_V; CYCLES(2); break;  /* CLV */
        case 0xB9: a = RD(ABY()); SETZN(a); CYCLES(4 + page); break;  /* LDA aby */
        case 0xBA: x = sp; SETZN(x); CYCLES(2); break;  /* TSX */
        case 0xBB: CYCLES(2); break;  /* illegal -> NOP */
        case 0xBC: y = RD(ABX()); SETZN(y); CYCLES(4 + page); break;  /* LDY abx */
        case 0xBD: a = RD(ABX()); SETZN(a); CYCLES(4 + page); break;  /* LDA abx */
        case 0xBE: x = RD(ABY()); SETZN(x); CYCLES(4 + page); break;  /* LDX aby */
        case 0xBF: { uint8_t v = RD(ABY()); a = v; x = v; SETZN(v); } CYCLES(4 + page); break;
        case 0xC0: { uint8_t v = RD(IMM()); A_CPY(v); } CYCLES(2); break;  /* CPY imm */
        case 0xC1: { uint8_t v = RD(INX()); A_CMP(v); } CYCLES(6); break;  /* CMP inx */
        case 0xC2: CYCLES(2); break;  /* illegal -> NOP */
        case 0xC3: { uint16_t e = INX(); uint8_t v = DEC8(RD(e)); WR(e, v); A_CMP(v); } CYCLES(6); break;  /* DCP inx */
        case 0xC4: { uint8_t v = RD(ZP()); A_CPY(v); } CYCLES(3); break;  /* CPY zp */
        case 0xC5: { uint8_t v = RD(ZP()); A_CMP(v); } CYCLES(3); break;  /* CMP zp */
        case 0xC6: { uint16_t e = ZP(); WR(e, DEC8(RD(e))); } CYCLES(5); break;  /* DEC zp */
        case 0xC7: { uint16_t e = ZP(); uint8_t v = DEC8(RD(e)); WR(e, v); A_CMP(v); } CYCLES(5); break;  /* DCP zp */
        case 0xC8: y++; SETZN(y); CYCLES(2); break;  /* INY */
        case 0xC9: { uint8_t v = RD(IMM()); A_CMP(v); } CYCLES(2); break;  /* CMP imm */
        case 0xCA: x--; SETZN(x); CYCLES(2); break;  /* DEX */
        case 0xCB: CYCLES(2); break;  /* illegal -> NOP */
        case 0xCC: { uint8_t v = RD(ABS_()); A_CPY(v); } CYCLES(4); break;  /* CPY abs */
        case 0xCD: { uint8_t v = RD(ABS_()); A_CMP(v); } CYCLES(4); break;  /* CMP abs */
        case 0xCE: { uint16_t e = ABS_(); WR(e, DEC8(RD(e))); } CYCLES(6); break;  /* DEC abs */
        case 0xCF: { uint16_t e = ABS_(); uint8_t v = DEC8(RD(e)); WR(e, v); A_CMP(v); } CYCLES(6); break;  /* DCP abs */
        case 0xD0: BRANCH_TAKE(!(p & F_Z)); break;  /* BNE rel */
        case 0xD1: { uint8_t v = RD(INY()); A_CMP(v); } CYCLES(5 + page); break;  /* CMP iny */
        case 0xD2: CYCLES(2); break;  /* illegal -> NOP */
        case 0xD3: { uint16_t e = INY(); uint8_t v = DEC8(RD(e)); WR(e, v); A_CMP(v); } CYCLES(6); break;  /* DCP iny */
        case 0xD4: CYCLES(2); break;  /* illegal -> NOP */
        case 0xD5: { uint8_t v = RD(ZPX()); A_CMP(v); } CYCLES(4); break;  /* CMP zpx */
        case 0xD6: { uint16_t e = ZPX(); WR(e, DEC8(RD(e))); } CYCLES(6); break;  /* DEC zpx */
        case 0xD7: { uint16_t e = ZPX(); uint8_t v = DEC8(RD(e)); WR(e, v); A_CMP(v); } CYCLES(6); break;  /* DCP zpx */
        case 0xD8: p &= (uint8_t)~F_D; CYCLES(2); break;  /* CLD */
        case 0xD9: { uint8_t v = RD(ABY()); A_CMP(v); } CYCLES(4 + page); break;  /* CMP aby */
        case 0xDA: CYCLES(2); break;  /* illegal -> NOP */
        case 0xDB: { uint16_t e = ABY(); uint8_t v = DEC8(RD(e)); WR(e, v); A_CMP(v); } CYCLES(7); break;  /* DCP aby */
        case 0xDC: CYCLES(2); break;  /* illegal -> NOP */
        case 0xDD: { uint8_t v = RD(ABX()); A_CMP(v); } CYCLES(4 + page); break;  /* CMP abx */
        case 0xDE: { uint16_t e = ABX(); WR(e, DEC8(RD(e))); } CYCLES(7); break;  /* DEC abx */
        case 0xDF: { uint16_t e = ABX(); uint8_t v = DEC8(RD(e)); WR(e, v); A_CMP(v); } CYCLES(7); break;  /* DCP abx */
        case 0xE0: { uint8_t v = RD(IMM()); A_CPX(v); } CYCLES(2); break;  /* CPX imm */
        case 0xE1: { uint8_t v = RD(INX()); A_SBC(v); } CYCLES(6); break;  /* SBC inx */
        case 0xE2: CYCLES(2); break;  /* illegal -> NOP */
        case 0xE3: { uint16_t e = INX(); uint8_t v = INC8(RD(e)); WR(e, v); A_SBC(v); } CYCLES(6); break;  /* ISC inx */
        case 0xE4: { uint8_t v = RD(ZP()); A_CPX(v); } CYCLES(3); break;  /* CPX zp */
        case 0xE5: { uint8_t v = RD(ZP()); A_SBC(v); } CYCLES(3); break;  /* SBC zp */
        case 0xE6: { uint16_t e = ZP(); WR(e, INC8(RD(e))); } CYCLES(5); break;  /* INC zp */
        case 0xE7: { uint16_t e = ZP(); uint8_t v = INC8(RD(e)); WR(e, v); A_SBC(v); } CYCLES(5); break;  /* ISC zp */
        case 0xE8: x++; SETZN(x); CYCLES(2); break;  /* INX */
        case 0xE9: { uint8_t v = RD(IMM()); A_SBC(v); } CYCLES(2); break;  /* SBC imm */
        case 0xEA: CYCLES(2); break;  /* NOP */
        case 0xEB: CYCLES(2); break;  /* illegal -> NOP */
        case 0xEC: { uint8_t v = RD(ABS_()); A_CPX(v); } CYCLES(4); break;  /* CPX abs */
        case 0xED: { uint8_t v = RD(ABS_()); A_SBC(v); } CYCLES(4); break;  /* SBC abs */
        case 0xEE: { uint16_t e = ABS_(); WR(e, INC8(RD(e))); } CYCLES(6); break;  /* INC abs */
        case 0xEF: { uint16_t e = ABS_(); uint8_t v = INC8(RD(e)); WR(e, v); A_SBC(v); } CYCLES(6); break;  /* ISC abs */
        case 0xF0: BRANCH_TAKE(p & F_Z); break;  /* BEQ rel */
        case 0xF1: { uint8_t v = RD(INY()); A_SBC(v); } CYCLES(5 + page); break;  /* SBC iny */
        case 0xF2: CYCLES(2); break;  /* illegal -> NOP */
        case 0xF3: { uint16_t e = INY(); uint8_t v = INC8(RD(e)); WR(e, v); A_SBC(v); } CYCLES(6); break;  /* ISC iny */
        case 0xF4: CYCLES(2); break;  /* illegal -> NOP */
        case 0xF5: { uint8_t v = RD(ZPX()); A_SBC(v); } CYCLES(4); break;  /* SBC zpx */
        case 0xF6: { uint16_t e = ZPX(); WR(e, INC8(RD(e))); } CYCLES(6); break;  /* INC zpx */
        case 0xF7: { uint16_t e = ZPX(); uint8_t v = INC8(RD(e)); WR(e, v); A_SBC(v); } CYCLES(6); break;  /* ISC zpx */
        case 0xF8: p |= F_D; CYCLES(2); break;  /* SED */
        case 0xF9: { uint8_t v = RD(ABY()); A_SBC(v); } CYCLES(4 + page); break;  /* SBC aby */
        case 0xFA: CYCLES(2); break;  /* illegal -> NOP */
        case 0xFB: { uint16_t e = ABY(); uint8_t v = INC8(RD(e)); WR(e, v); A_SBC(v); } CYCLES(7); break;  /* ISC aby */
        case 0xFC: CYCLES(2); break;  /* illegal -> NOP */
        case 0xFD: { uint8_t v = RD(ABX()); A_SBC(v); } CYCLES(4 + page); break;  /* SBC abx */
        case 0xFE: { uint16_t e = ABX(); WR(e, INC8(RD(e))); } CYCLES(7); break;  /* INC abx */
        case 0xFF: { uint16_t e = ABX(); uint8_t v = INC8(RD(e)); WR(e, v); A_SBC(v); } CYCLES(7); break;  /* ISC abx */
        }
        if (cyc == 0) cyc = 2;
        if (cpu_stall) {
            cyc += cpu_stall;         /* OAM DMA: real halted cycles */
            cpu_stall = 0;
        }
        cpu.cycles += (uint32_t)cyc;
        done += cyc;
        ins++;
    }
